version: "3.2"

services:
  postgres:
    image: postgres:9-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - backend
    volumes:
      - ./init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh:ro
      - postgres-data:/var/lib/postgresql/data

  zookeeper:
    image: janobono/zookeeper:3
    networks:
      - backend
    volumes:
      - zookeeper-log:/zookeeper/log
      - zookeeper-data:/zookeeper/data

  kafka:
    image: janobono/kafka:2
    depends_on:
      - zookeeper
    networks:
      - backend
    volumes:
      - kafka-log:/kafka/log
      - kafka-data:/kafka/data

  backend:
    image: janobono/final-nut-backend:latest
    environment:
      - NUT_DB_URL=jdbc:postgresql://postgres:5432/quarkus
      - NUT_DB_USER=quarkus
      - NUT_DB_PASSWORD=quarkus
      - NUT_KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - 8080:8080
    networks:
      - backend
    depends_on:
      - postgres
      - kafka

  frontend:
    image: janobono/final-nut-frontend:latest
    ports:
      - 80:3000

networks:
  backend:

volumes:
  postgres-data:
  zookeeper-log:
  zookeeper-data:
  kafka-log:
  kafka-data:
